spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: ${db.ddl}
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: ${db.sql.init}
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

kakao:
  REST_KEY: ${kakao.REST_KEY}
  REDIRECT_URI: ${kakao.REDIRECT_URI}